.\" @(#)$RCSfile: libdavix.man,v $ $Revision: 1 $ $Date: 2014/05/24 $ CERN Adrien Devresse
.\" Copyright (C) 2014 by CERN
.\" All rights reserved
.\"
.TH LIBDAVIX 3 "$Date: 2014/05/24 $" libdavix 
.SH NAME
libdavix \- shared library for HTTP I/O
	              
.SH DESCRIPTION
libdavix is a C++ shared library for high performance remote I/O and resources management with HTTP Based protocols.
.br
.PP
libdavix aims to be a complete, reliable and performant I/O layer for Cloud, Grid and Web storage systems.
.br
It supports the protocol Http (http(s)://), WebDav (dav(s)://) and S3 (s3(s)://). 
.br
.PP
See libdavix doxygen documentation for more details.
.PP	


.SH SEE ALSO
.BR davix-get(1), davix-put(1), davix-mkdir(1), davix-rm(1), davix-ls(1)
.BR

.SH LINKS
.BR http://dmc.web.cern.ch/projects/davix/home


.SH AUTHORS
Adrien Devresse <adrien.devresse@cern.ch>, IT-SDC-ID, CERN
